---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Cloning the kube-state-metrics repository.
      git:
        repo: 'https://github.com/kubernetes/kube-state-metrics.git'
        dest: ~/kube-state-metrics

    - name: Building a list of manifests in the repository.
      find:
        paths: ~/kube-state-metrics/kubernetes
        pattern: '*.yaml'
      register: manifest_list

    - name: Enabling cluster level metrics collection.
      k8s:
        definition: "{{ lookup('template', {{ item.path }} ) | from_yaml_all | list }}"
      loop: "{{ manifest_list }}"
      loop_control:
        label: "absolute path"

    - name: Deploying the datadog agent.
      k8s:
        definition: "{{ lookup('template', ./files/templates/Datadog/datadog_integration.yml.j2 | from_yaml }}"
