---
- hosts: k8s_master
  gather_facts: no
  tasks:
    - name: Deploying MetalLB.
      become: yes
      shell: kubectl apply -f https://raw.githubusercontent.com/google/metallb/v0.7.3/manifests/metallb.yaml

    - name: Configuring MetalLB.
      become: yes
      k8s:
        definition: "{{ lookup('template', '../../files/templates/MetalLB/metallb_config.yml.j2') | from_yaml_all | list }}"
