---
- hosts: k8s_master:k8s_nodes
  tasks:
    - name: Installing nfs-common.
      become: yes
      apt:
        name: nfs-common


- hosts: k8s_master
  tasks:
    - name: Deploying the Role Binding for the NFS Provisioner to Kubernetes.
      become: yes
      k8s:
        definition: "{{ lookup('template', '../../files/templates/NFS/nfs_role_binding.yml.j2') | from_yaml_all | list }}"        

    - name: Deploying the NFS Provisioner to Kubernetes.
      become: yes
      k8s:
        definition: "{{ lookup('template', '../../files/templates/NFS/nfs_provisioner.yml.j2') | from_yaml_all | list }}"        

    - name: Deploying the NFS Storage Class to Kubernetes.
      become: yes
      k8s:
        definition: "{{ lookup('template', '../../files/templates/NFS/nfs_storage_class.yml.j2') | from_yaml_all | list }}"        
