---
#Deploy the LXCs to your Proxmox server
- import_playbook: Playbooks/deploy_lxc_containers.yml

#Prepare CentOS for Kubernetes
- import_playbook: Playbooks/install_base_packages.yml
- import_playbook: Playbooks/perform_miscellaneous_tasks.yml

#Bootstrap Kubernetes
- import_playbook: Playbooks/bootstrap_kubernetes.yml