---
- hosts: proxmox_server
  tasks: 
      - name: Stopping the Master container
        shell: pct stop {{ k8s_master_id }}
        ignore_errors: yes

      - name: Stopping the Node 1 container
        shell: pct stop {{ k8s_node1_id }}
        ignore_errors: yes

      - name: Stopping the Node 2 container
        shell: pct stop {{ k8s_node2_id }}
        ignore_errors: yes

      - name: Stopping the Node 3 container
        shell: pct stop {{ k8s_node3_id }}
        ignore_errors: yes

      - name: Destroying the Master container
        shell: pct destroy {{ k8s_master_id }}
        ignore_errors: yes
 
      - name: Destroying the Node 1 container
        shell: pct destroy {{ k8s_node1_id }}
        ignore_errors: yes

      - name: Destroying the Node 2 container
        shell: pct destroy {{ k8s_node2_id }}
        ignore_errors: yes

      - name: Destroying the Node 3 container
        shell: pct destroy {{ k8s_node3_id }}
        ignore_errors: yes

      - name: Deleting the resource pool
        shell: pvesh delete /pools/{{ k8s_resource_pool }}
        ignore_errors: yes

      - name: Removing overlay module from /etc/modules
        replace: 
          path: /etc/modules
          regexp: '^overlay$'
        ignore_errors: yes

      - name: Stopping overlay module on Proxmox server.
        modprobe:
          name: overlay
          state: absent
        ignore_errors: yes