---
- hosts: proxmox_server
  tasks:
      - name: Creating a resource pool
        shell: pvesh create /pools -poolid "{{ k8s_resource_pool }}" --Comment "Kubernetes Cluster made from CentOS 7 Linux Containers"

      - name: Downloading the newest CentOS LXC template
        shell: pveam download {{ template_storage }} {{ centos_template }}

      - name: Provisioning a Kubernetes Master container
        shell: >
            pct create {{ k8s_master_id }}
            {{ template_storage }}:vztmpl/{{ centos_template }}
            --pool "{{ k8s_resource_pool }}" 
            --description "Kubernetes Master"
            --hostname "{{ k8s_master_hn }}" 
            --memory "{{ k8s_master_mem }}" 
            --net0 "name=eth0,bridge={{ k8s_master_bridge }},ip={{ k8s_master_ip }},gw={{ k8s_master_gw }},ip6=dhcp" 
            --nameserver "{{ k8s_nameserver }}"
            --searchdomain "{{ k8s_searchdomain }}"
            --ostype "centos" 
            --swap "0" 
            --storage "{{ k8s_master_stg }}" 
            --ssh-public-keys "{{ k8s_ssh_key }}"

      - name: Pausing for 5 seconds to allow the container to finish being created
        wait_for: timeout=5

      - name: Resizing the volume for the Master container
        shell: pct resize {{ k8s_master_id }} rootfs {{ k8s_master_size }} 
      
      - name: Provisioning Kubernetes Node 1 container
        shell: >
            pct create {{ k8s_node1_id }}
            {{ template_storage }}:vztmpl/{{ centos_template }}
            --pool "{{ k8s_resource_pool }}" 
            --description "Kubernetes Node 1"
            --hostname "{{ k8s_node1_hn }}" 
            --memory "{{ k8s_node1_mem }}" 
            --net0 "name=eth0,bridge={{ k8s_node1_bridge }},ip={{ k8s_node1_ip }},gw={{ k8s_node1_gw }},ip6=dhcp" 
            --nameserver "{{ k8s_nameserver }}"
            --searchdomain "{{ k8s_searchdomain }}"
            --ostype "centos" 
            --swap "0" 
            --storage "{{ k8s_node1_stg }}" 
            --ssh-public-keys "{{ k8s_ssh_key }}"

      - name: Pausing for 5 seconds to allow the container to finish being created
        wait_for: timeout=5

      - name: Resizing the volume for the Node 1 container
        shell: pct resize {{ k8s_node1_id }} rootfs {{ k8s_node1_size }} 
      
      - name: Provisioning Kubernetes Node 2 container
        shell: >
            pct create {{ k8s_node2_id }}
            {{ template_storage }}:vztmpl/{{ centos_template }}
            --pool "{{ k8s_resource_pool }}" 
            --description "Kubernetes Node 2"
            --hostname "{{ k8s_node2_hn }}" 
            --memory "{{ k8s_node2_mem }}" 
            --net0 "name=eth0,bridge={{ k8s_node2_bridge }},ip={{ k8s_node2_ip }},gw={{ k8s_node2_gw }},ip6=dhcp"
            --nameserver "{{ k8s_nameserver }}"
            --searchdomain "{{ k8s_searchdomain }}" 
            --ostype "centos" 
            --swap "0" 
            --storage "{{ k8s_node2_stg }}" 
            --ssh-public-keys "{{ k8s_ssh_key }}"

      - name: Pausing for 5 seconds to allow the container to finish being created
        wait_for: timeout=5

      - name: Resizing the volume for the Node 2 container
        shell: pct resize {{ k8s_node2_id }} rootfs {{ k8s_node2_size }} 
      
      - name: Provisioning Kubernetes Node 3 container
        shell: >
            pct create {{ k8s_node3_id }}
            {{ template_storage }}:vztmpl/{{ centos_template }}
            --pool "{{ k8s_resource_pool }}" 
            --description "Kubernetes Node 3"
            --hostname "{{ k8s_node3_hn }}" 
            --memory "{{ k8s_node3_mem }}" 
            --net0 "name=eth0,bridge={{ k8s_node3_bridge }},ip={{ k8s_node3_ip }},gw={{ k8s_node3_gw }},ip6=dhcp" 
            --nameserver "{{ k8s_nameserver }}"
            --searchdomain "{{ k8s_searchdomain }}" 
            --ostype "centos" 
            --swap "0" 
            --storage "{{ k8s_node3_stg }}" 
            --ssh-public-keys "{{ k8s_ssh_key }}"

      - name: Pausing for 5 seconds to allow the container to finish being created
        wait_for: timeout=5

      - name: Resizing the volume for the Node 3 container
        shell: pct resize {{ k8s_node3_id }} rootfs {{ k8s_node3_size }} 

      - name: Starting the containers for the first time
        shell: pct start {{ k8s_master_id }} && pct start {{ k8s_node1_id }} && pct start {{ k8s_node2_id }} && pct start {{ k8s_node3_id }}

      - name: Installing openssh-server on the master 
        shell: lxc-attach -n {{ k8s_master_id }} -- yum install -y openssh-server

      - name: Enabling & starting sshd on the master
        shell: lxc-attach -n {{ k8s_master_id }} -- systemctl enable --now sshd

      - name: Installing openssh-server on the Node 1 
        shell: lxc-attach -n {{ k8s_node1_id }} -- yum install -y openssh-server

      - name: Enabling & starting sshd on the Node 1
        shell: lxc-attach -n {{ k8s_node1_id }} -- systemctl enable --now sshd

      - name: Installing openssh-server on the Node 2 
        shell: lxc-attach -n {{ k8s_node2_id }} -- yum install -y openssh-server

      - name: Enabling & starting sshd on the Node 2
        shell: lxc-attach -n {{ k8s_node2_id }} -- systemctl enable --now sshd

      - name: Installing openssh-server on the Node 3 
        shell: lxc-attach -n {{ k8s_node3_id }} -- yum install -y openssh-server

      - name: Enabling & starting sshd on the Node 3
        shell: lxc-attach -n {{ k8s_node3_id }} -- systemctl enable --now sshd
