---
- hosts: proxmox_server
  tasks:
      - name: Creating a resource pool for the compute resources.
        shell: pvesh create /pools -poolid "{{ k8s_resource_pool }}" --Comment "Kubernetes Cluster"

      - name: Downloading the newest CentOS qcow2 image.
        get_url:
          url: "{{ qcow2_image }}"
          dest: "{{ qcow2_download_location }}"CentOS7.qcow2c

      - name: Provisioning a virtual machine for the Kubernetes master.