---
- hosts: k8s_master:k8s_nodes
  tasks:
      - name: Add Kubernetes repo to yum
        yum_repository:
            name: Kubernetes
            description: "Kubernetes repository to install kubeadm"
            baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
            gpgcheck: yes
            repo_gpgcheck: yes
            gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

      - name: Installing the epel repo
        yum:
            name: epel-release

      - name: Installing base packages 
        yum:
            name: ['vim', 'wget', 'tree', 'curl', 'mlocate', 'nmap', 'net-tools', 'bind-utils', 'lsof', 'htop', 'iotop', 'bmon', 'sysstat']

      - name: Install required packages to bootstrap a kubernetes cluster
        yum:
            name: ['kubelet', 'kubeadm', 'kubectl']
