---
- hosts: proxmox_server
  tasks: 
    - name: Enable overlay module
      shell: echo overlay >> /etc/modules

    - name: Configure LXC configuration to add privileges for nested virtualization
      shell: |
        cat >> /etc/pve/lxc/170.conf <<'EOF'
        lxc.apparmor.profile: unconfined
        lxc.cap.drop: 
        lxc.cgroup.devices.allow: a
        lxc.mount.auto: proc:rw sys:rw
        EOF

- hosts: k8s_master:k8s_nodes
  tasks:
      - name: Create database for mlocate
        shell: updatedb

      - name: Enable systemd module for docker-ce
        systemd: 
            state: started
            name: docker
            enabled: yes

      - name: Enable systemd module for kubelet
        systemd:
            state: started
            name: kubelet
            enabled: yes

      - name: Enable systemd module for rc-local
        systemd:
            state: started
            name: rc-local
            enabled: yes

      - name: Set execution bit for rc.local file
        shell: chmod +x /etc/rc.local

      - name: Enabled shared most for host mounts
        shell: >
          echo '#!/bin/sh -e
          mount --make-rshared /' > /etc/rc.local

      - name: Copy docker.service for override
        shell:  cp /{lib,etc}/systemd/system/docker.service

      - name: Reboot hosts
        reboot: