---
- hosts: proxmox_server
  tasks: 
    - name: Enable overlay module
      shell: echo overlay >> /etc/modules

    - name: Adding additional privileges to the Master container
      shell: |
        echo "
        lxc.apparmor.profile: unconfined
        lxc.cap.drop: 
        lxc.cgroup.devices.allow: a
        lxc.mount.auto: proc:rw sys:rw" >> /etc/pve/lxc/{{ k8s_master_id }}.conf

    - name: Adding additional privileges to the Node 1 container
      shell: |
        echo "
        lxc.apparmor.profile: unconfined
        lxc.cap.drop: 
        lxc.cgroup.devices.allow: a
        lxc.mount.auto: proc:rw sys:rw" >> /etc/pve/lxc/{{ k8s_node1_id }}.conf

    - name: Adding additional privileges to the Node 2 container
      shell: |
        echo "
        lxc.apparmor.profile: unconfined
        lxc.cap.drop: 
        lxc.cgroup.devices.allow: a
        lxc.mount.auto: proc:rw sys:rw" >> /etc/pve/lxc/{{ k8s_node2_id }}.conf

    - name: Adding additional privileges to the Node 3 container
      shell: |
        echo "
        lxc.apparmor.profile: unconfined
        lxc.cap.drop: 
        lxc.cgroup.devices.allow: a
        lxc.mount.auto: proc:rw sys:rw" >> /etc/pve/lxc/{{ k8s_node3_id }}.conf

    - name: Enabling overlay kernel module on Proxmox server
      lineinfile:
        path: /etc/modules
        line: 'overlay'

    - name: Starting overlay module on Proxmox server
      modprobe: 
        name: overlay


- hosts: k8s_master:k8s_nodes
  tasks:
      - name: Create database for mlocate
        shell: updatedb

      - name: Enabling the systemd module for docker-ce
        systemd: 
            state: started
            name: docker
            enabled: yes

      - name: Enabling the systemd module for kubelet
        systemd:
            state: started
            name: kubelet
            enabled: yes

      - name: Enabling the systemd module for rc-local
        systemd:
            state: started
            name: rc-local
            enabled: yes

      - name: Setting the execution bit for rc.local
        file:
          path: /etc/rc.local
          mode: a+x

      - name: Enabling the shared mount
        shell: |
          echo "#!/bin/sh -e
          mount --make-rshared /" > /etc/rc.local

      - name: Copying the docker.service for override
        shell:  cp /{lib,etc}/systemd/system/docker.service

      - name: Rebooting the containers
        reboot: